package firm.seytihanlaw.slawfirm.model;

public enum ATTORNEY {
    AHMET_SEYITHANOGLU("AHMET_SEYITHANOGLU"),
    SINAN_TURHAN("SINAN_TURHAN"),
    SINAN_SARI("SINAN_SARI"),
    CENAB_YAVUZ("CENAB_YAVUZ"),
    NURULLAH_CELIK("NURULLAH_CELIK"),
    YUSUF_MENEK("YUSUF_MENEK"),
    MELIKSAH_DURMUS("MELIKSAH_DURMUS");

    ATTORNEY(String attorneyName) {
    }
}
